---
- hosts: all
  become: true
  tasks:

  - name: Install Apache
    package:
      name: "{{ apache_pkg }}"
      state: latest
  
  - name: Start Apache service for RedHat
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"

  - name: Check Apache status
    command: "systemctl status {{ apache_pkg }}"
    register: svc_facts
  
  - name: Print Apache status
    debug:
      msg: "{{ ansible_hostname }}: {{ svc_facts.stdout_lines }}"  