---
- hosts: all
  become: yes
  tasks:
    - name: "Check if APACHE is installed"
      package_facts:
        manager: "auto"
    - name: "Apache result"
      debug:
         msg: "Apache found"
      when: ("'httpd' in ansible_facts.packages" and ansible_distribution == "RedHat") or 
            ("'apache2' in ansible_facts.packages" and ansible_distribution == "Ubuntu")
    - name: "Apache result"
      debug:
         msg: "Apache NOT found"
      when: ("'httpd' in ansible_facts.packages" and ansible_distribution == "RedHat") or 
            ("'apache2' in ansible_facts.packages" and ansible_distribution == "Ubuntu")